### ISSUE TITLE
RTP KMZ layers file

### ISSUE THREAD

**Issue by BryanGK** [bcgov/connectivity-RTP#87]
As an Applicant
Having this resource (.kmz layers) 
Will indirectly improve the quality of the connectivity solutions I present in my RTP response

Definition of Ready:
- [ ] All input resources compiled and ready to layer into compiled .kmz file

Definition of Done:
- [x] KMZ file has all 5 layers
- [x] KMZ file is stored in file server for applicant upload
- [x] All layers contain most complete and most recent data able to been relied on
- [x] Data is anonymized (no exact locations, distances) to protect community confidentiality
- [x] Posted to BC Data Catalogue
